### ISSUE TITLE
Problem with Icon class e Font awesome

### ISSUE THREAD

**Issue by evaldobarbosa** [cagilo/cagilo#1]
I am trying to display home icon with
```
<x-icon path="fa.home" />
```
And getting **Call to undefined method Cagilo\UI\Components\Icon::withName()** as result.

My "icon" session in cagilo.php is like recommended on website documentation and font-awesome (only unzipped) is in the atorage/app folder.

**Comment by tabuna** [comment]
Hey @evaldobarbosa, this should be fixed with a minor update. You can update the version by running:

```php
composer update cagilo/cagilo --with-dependencies
```

Also, don't forget to clear the cache afterward.

**Comment by evaldobarbosa** [comment]
Works.

Thanks.
